name: CI
erbs:
  node: circleci/node@1.1.6
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
jobs:
    build-and-test:
        executor:
          name: node/default
        steps: 
          - uses: actions/checkout@v2
          - run: npm install
          - run: npm run test